"""Surface inventory, registration coverage and generated browser contracts (stdlib only)."""
from html.parser import HTMLParser
import json
from pathlib import Path
import re
import subprocess

MANIFEST = '.ui-surfaces.json'
HOME = Path(__file__).resolve().parents[1]
REQUIRED = ('cedar-workspace', 'cedar-embeddable-designer', 'cedar-embeddable-editor', 'cedar-template-designer', 'cedar-openview')
SECTIONS = ('Management', 'Menus', 'Resource Dialogs', 'Confirmation / Warning / Error', 'Metadata Editor', 'Template Designer', 'Workspace', 'OpenView')
CONTRACTS = json.loads((HOME / 'surfaces/contracts.json').read_text())['contracts']


def browser_source():
    return '// GENERATED by cedarcli check design-tokens --sync-surfaces. Do not edit.\n' + \
        'const CONTRACTS = ' + json.dumps(CONTRACTS, indent=2) + ';\n' + \
        'const TOKEN_DEFAULTS = ' + json.dumps(json.loads((HOME / 'surfaces/token-defaults.json').read_text()), indent=2) + ';\n' + (HOME / 'surfaces/browser.mjs').read_text()


def safe_file(repo, name):
    if not isinstance(name, str) or not name or Path(name).is_absolute() or '..' in Path(name).parts:
        raise ValueError(f'Invalid repository-relative path: {name}')
    result = repo / name
    if not result.resolve().is_relative_to(repo.resolve()):
        raise ValueError(f'Path escapes repository: {name}')
    return result


class Surfaces(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=False)
        self.found = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        classes = (attrs.get('class') or '').split()
        # Semantic markup plus the existing Angular/native menu conventions.
        kind = ('dialog' if tag == 'dialog' or attrs.get('role') in ('dialog', 'alertdialog') or
                'cedar-modal-surface' in classes else
                'menu' if tag == 'mat-menu' or attrs.get('role') == 'menu' or
                any(c in classes for c in ('resource-menu', 'user-menu-dropdown', 'profile-menu-dropdown', 'dropdown-panel')) or
                tag == 'details' and any('menu' in c for c in classes) else
                'summary' if tag == 'details' and any(c in classes for c in ('validation-summary', 'metadata-quality')) else None)
        if kind:
            self.found.append({'kind': kind, 'anchor': self.get_starttag_text(), 'line': self.getpos()[0]})

    handle_startendtag = handle_starttag


def authored_files(repo):
    names = subprocess.check_output(['git', '-C', str(repo), 'ls-files', '-z', '--cached', '--others', '--exclude-standard'], text=True).split('\0')
    for name in sorted(set(names)):
        p = Path(name)
        parts = p.parts[1:] if p.parts and p.parts[0].endswith('-src') else p.parts
        if (parts and parts[0] in ('src', 'app') and p.suffix in ('.html', '.ts') and
                '.spec.' not in name and not {'assets', 'fixtures', 'node_modules'}.intersection(p.parts) and (repo / p).is_file()):
            yield name


def load(repo):
    data = json.loads((repo / MANIFEST).read_text())
    if data.get('schema') != 1 or not isinstance(data.get('surfaces'), list):
        raise ValueError('Invalid surface registry schema')
    if (data.get('browserHelper') is not None or any(s.get('contract') for s in data['surfaces'] if isinstance(s, dict))) and (not isinstance(data.get('browserHelper'), str) or not re.fullmatch(r'(?:browser|visual)/tests/surface-contracts\.generated\.mjs', data['browserHelper'])):
        raise ValueError('browserHelper must be the generated helper in the browser test directory')
    if not data['surfaces'] or any(not isinstance(s, dict) for s in data['surfaces']):
        raise ValueError('Registry must contain surface objects')
    for surface in data['surfaces']:
        if not isinstance(surface.get('id'), str) or not isinstance(surface.get('name'), str):
            raise ValueError('Surface ID and name must be strings')
        if not isinstance(surface.get('debt', {}), dict):
            raise ValueError('Surface debt must be an object')
        if not isinstance(surface.get('source', []), list) or any(not isinstance(item, dict) or not isinstance(item.get('file'), str) or not isinstance(item.get('anchor'), str) for item in surface.get('source', [])):
            raise ValueError('Source references need file and anchor strings')
    return data


def validate(repo):
    errors = []
    # Legacy browser apps keep the real package beneath <app>-src; CI may name
    # the checkout "consumer", so repository directory names cannot identify it.
    packages = [repo / 'package.json', *sorted(repo.glob('*-src/package.json'))]
    package = next((json.loads(p.read_text()) for p in packages if p.is_file()
                    and json.loads(p.read_text()).get('name')), {})
    if not package and (repo / MANIFEST).exists():
        return ['Registry has no owning package']
    if package.get('name') not in REQUIRED and repo.name not in REQUIRED and not (repo / MANIFEST).exists():
        return errors
    if not (repo / MANIFEST).exists():
        return [f'Missing {MANIFEST}']
    data = load(repo)
    if data.get('repo') != package.get('name'):
        errors.append('Registry owner does not match package name')
    ids = set()
    for surface in data['surfaces']:
        sid = surface.get('id', '')
        if not re.fullmatch(r'[a-z][a-z0-9.-]+', sid) or sid in ids:
            errors.append(f'Invalid or duplicate surface ID: {sid}')
        ids.add(sid)
        if surface.get('section') not in SECTIONS:
            errors.append(f'{sid}: unknown inventory section')
        if not surface.get('name'):
            errors.append(f'{sid}: missing name')
        if surface.get('contract'):
            if surface['contract'] not in CONTRACTS:
                errors.append(f'{sid}: unknown contract')
            if not surface.get('selector') or not surface.get('scenario') or surface.get('states') != (['collapsed', 'expanded'] if surface['contract'].endswith('summary') else ['open']):
                errors.append(f'{sid}: selector, scenario and applicable states are required')
            if not surface.get('source'):
                errors.append(f'{sid}: missing source registration')
            if not surface.get('test'):
                errors.append(f'{sid}: missing browser test')
            else:
                test = safe_file(repo, surface['test'])
                if not test.is_file() or 'surfaceCases(' not in test.read_text() or 'checkSurface(' not in test.read_text():
                    errors.append(f'{sid}: missing registry-driven browser test: {surface["test"]}')
        for prop, debt in surface.get('debt', {}).items():
            if prop not in CONTRACTS.get(surface.get('contract'), {}) or not isinstance(debt, dict) or set(debt) != {'actual', 'expected', 'reason'} or not all(isinstance(v, str) and v.strip() for v in debt.values()) or debt['actual'] == debt['expected']:
                errors.append(f'{sid}: invalid rendered debt for {prop}')
        for source in surface.get('source', []):
            path = safe_file(repo, source['file'])
            if not path.is_file() or not source.get('anchor') or source['anchor'] not in path.read_text():
                errors.append(f'{sid}: stale source reference: {source}')
    for surface in data['surfaces']:
        if surface.get('parent') and surface['parent'] not in ids:
            errors.append(f'{surface["id"]}: missing parent {surface["parent"]}')
        seen = {surface['id']}
        parent = surface.get('parent')
        while parent in ids:
            if parent in seen:
                errors.append(f'{surface["id"]}: hierarchy cycle')
                break
            seen.add(parent)
            parent = next(s.get('parent') for s in data['surfaces'] if s['id'] == parent)
    for name in authored_files(repo):
        parser = Surfaces()
        source_text = (repo / name).read_text()
        parser.feed(source_text)
        if package.get('name') == 'cedar-openview' and name.endswith('-routing.module.ts'):
            for route in re.finditer(r'\bpath\s*:\s*([\"\'])(.*?)\1', source_text):
                if not any(any(source['file'] == name and source['anchor'] == route.group(0)
                               for source in surface.get('source', [])) for surface in data['surfaces']):
                    errors.append(f'{name}: unregistered route {route.group(2)!r}')
        for found in parser.found:
            registered = [s for s in data['surfaces'] if s.get('contract') and any(
                source['file'] == name and source['anchor'] in found['anchor'] for source in s.get('source', []))]
            if not registered:
                errors.append(f'{name}:{found["line"]}: unregistered {found["kind"]}')
    if not data.get('browserHelper'):
        return errors
    generated = safe_file(repo, data['browserHelper'])
    if not generated.is_file() or generated.read_text() != browser_source():
        errors.append('Browser contract helper is stale; run --sync-surfaces')
    declaration = generated.with_suffix('.d.mts')
    if not declaration.is_file() or declaration.read_text() != (HOME / 'surfaces/browser.d.mts').read_text():
        errors.append('Browser contract types are stale; run --sync-surfaces')
    return errors


def findings(repo, ref=None):
    try:
        errors = validate(repo)
        if ref and (repo / MANIFEST).exists():
            previous = subprocess.run(['git', '-C', str(repo), 'show', f'{ref}:{MANIFEST}'], capture_output=True, text=True)
            if previous.returncode == 0:
                old = {s['id']: s.get('debt', {}) for s in json.loads(previous.stdout)['surfaces']}
                for surface in load(repo)['surfaces']:
                    for prop, allowance in surface.get('debt', {}).items():
                        if old.get(surface['id'], {}).get(prop) != allowance:
                            errors.append(f"{surface['id']}: feature changes cannot add or expand rendered debt")
    except (ValueError, KeyError, TypeError, OSError) as exc:
        errors = [f'Invalid surface registry: {exc}']
    for index, error in enumerate(errors):
        yield {'id': f'surface-{index}', 'file': MANIFEST, 'line': 1,
               'rule': 'surface-coverage', 'property': 'registration', 'value': error,
               'severity': 'gate', 'status': 'new'}


def sync(repo):
    if not (repo / MANIFEST).exists():
        return
    data = load(repo)
    if not data.get('browserHelper'):
        return
    output = safe_file(repo, data['browserHelper'])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(browser_source())
    output.with_suffix('.d.mts').write_text((HOME / 'surfaces/browser.d.mts').read_text())


def markdown(root):
    for name in REQUIRED:
        errors = validate(root / name)
        if errors:
            raise ValueError(f'{name}: ' + '; '.join(errors))
    registries = [load(root / name) for name in REQUIRED]
    nodes = [s for data in registries for s in data['surfaces']]
    sections = SECTIONS
    lines = ['# Modern Workspace — UI Pages & Surfaces', '', '<!-- Generated from .ui-surfaces.json registries. Do not edit this file. -->', '']
    def render(node, depth=0):
        if node.get('inventory') is False:
            return
        lines.append('  ' * depth + '- ' + node['name'])
        for child in nodes:
            if child.get('parent') == node['id']:
                render(child, depth + 1)
    for section in sections:
        lines += ['## ' + section, '']
        for node in nodes:
            if node.get('section') == section and not node.get('parent'):
                render(node)
        lines.append('')
    return '\n'.join(lines)
